language: objective-c
osx_image: xcode8.1
before_install: true
install: true
git:
  submodules: false
before_script:
  - git submodule update --init --recursive
script:
  - script/build
xcode_workspace: ReactiveObjC.xcworkspace
cache:
  directories:
    - $HOME/.cocoapods
matrix:
  include:
    - script:
      - pod repo update --silent
      - pod lib lint ReactiveObjC.podspec
      env:
        - JOB=PODSPEC
notifications:
  email: false
  slack:
    secure: C9QTry5wUG9CfeH3rm3Z19R5rDWqDO7EhHAqHDXBxT6CpGRkTPFliJexpjBYB4sroJ8CiY5ZgTI2sjRBiAdGoE5ZQkfnwSoKQhWXkwo19TnbSnufr3cKO2SZkUhBqOlZcA+mgfjZ7rm2wm7RhpCR/4z8oBXDN4/xv0U5R2fLCLE=
